# Put in /etc/netplan/51-eip.yaml and then sudo netplan apply
network:
  version: 2
  renderer: networkd
  ethernets:
    lo:
      match:
        name: lo
      addresses:
        - 194.182.162.5/32
