#cloud-config
write_files:
- content: |
    {
      "DOMAIN": "${DOMAIN}",
      "EMAIL": "${EMAIL}",
      "KEY": "${ACCESS_KEY}"
    }
  path: /tmp/conf/config.json

runcmd:
 - node /home/ubuntu/setup.js